"""
Rôle de ce fichier dans Django :
Ce fichier de migration décrit la création initiale des tables de l'application conges.
Django l'utilise pour synchroniser les modèles Python avec la base SQLite.
"""

# Generated by Django 6.0.4 on 2026-04-29 16:41

import django.db.models.deletion  # Django utilise ce module pour appliquer la suppression en cascade.
from django.conf import settings  # La migration lit le modèle utilisateur configuré dans les settings.
from django.db import migrations, models  # Ces classes décrivent les opérations et champs de base de données.


class Migration(migrations.Migration):
    """Décrit la première migration de l'application conges.

    Cette classe contient les dépendances et opérations nécessaires pour créer les tables.
    Elle retourne une définition lue par la commande migrate.
    """

    initial = True  # Cette migration est la première de l'application.

    dependencies = [  # Les dépendances garantissent que la table utilisateur existe avant Employe.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # On dépend du modèle User actif de Django.
    ]

    operations = [  # Les opérations décrivent les changements à appliquer à la base.
        migrations.CreateModel(
            name='Employe',  # Cette opération crée la table du modèle Employe.
            fields=[  # Ces champs deviennent les colonnes de la table.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_conges', models.IntegerField(default=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeConge',  # Cette opération crée la table du modèle DemandeConge.
            fields=[  # Ces champs deviennent les colonnes de la table.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_conge', models.CharField(choices=[('annuel', 'Congé annuel'), ('maladie', 'Congé maladie'), ('autre', 'Autre')], max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conges.employe')),
            ],
        ),
    ]
